Add optimization mods for the modpack
kiskoza/Above-and-Beyond pull request #5
Opened 2024-11-10 12:44 UTC by GaryBlackbourne

One of the main problems we face is with performance. I have added some mods, to ease the load on memory and the CPU.

Mods added:
- Magnesium
- Sulfuric
- Helium
- RoadRunner

2024-11-10 12:46 UTC, GaryBlackbourne commented
The links for the mods:
- [Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged)
- [Sulfuric](https://www.curseforge.com/minecraft/mc-mods/phosphor-reforged)
- [Helium](https://www.curseforge.com/minecraft/mc-mods/hydrogen-reforged)
- [RoadRunner](https://www.curseforge.com/minecraft/mc-mods/roadrunner)

2024-11-11 22:05 UTC, kiskoza commented
My local setup crashed with these new mods. The error is coming from Helium, which states on its readme that it might be incompatible with Create. Some of the commenters recommends ferritecore instead, please take a look at it and see it it has any overlap / incompatibility with the other three.

Also, when you're ready, don't forget to include the new mods in the modlist.html file as well (bonus point for writing a script to generate that file)

2024-11-17 14:21 UTC, kiskoza requested changes
Also, please add the new mods to the modlist.html and write an entry to the changelog

2024-11-17 14:21 UTC, kiskoza commented on manifest.json
> +      "fileID": 3435176,
This one seesm to be the fileID for ferritecore 2.0.7. Before this PR we used to have 2.1.0 and the lastest one is 2.1.1. Please take a look at it again to make sure we have the best option here.

2024-11-18 17:35 UTC, kiskoza approved these changes

2024-11-18 17:37 UTC, merged